twig:
    default_path: '/%kernel.project_dir%/UI/templates'
    paths:
        'src/UI/templates': ~
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
