services:
  shop-nginx:
    image: nginx:stable-alpine
    depends_on:
      - shop-php
    networks:
      - shop-project
    volumes:
      - ".docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - ".:/var/www/html"

  shop-php:
    build:
      context: .docker/
    volumes:
      - ".:/var/www/html"
    networks:
      - shop-project

  shop-redis:
    image: redis:7-alpine
    entrypoint: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru --requirepass test321
    volumes:
      - "shopredis:/data:z"
    networks:
      - shop-project

  shop-db:
    image: mariadb:10.11.6
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: shop
      MYSQL_DATABASE: shop_db
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - shop-project

  shop-vue:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - "./frontend:/app"
    command: ["sh", "-c", "npm install && npm run dev -- --host"]
    networks:
      - shop-project

  shop-mailer:
    image: schickling/mailcatcher
    networks:
      - shop-project

networks:
  shop-project:
    external: true

volumes:
  dbdata: ~
  shopredis: ~