services:
  shop-php:
    extra_hosts:
      - host.docker.internal:host-gateway

  shop-nginx:
    ports:
      - "8080:80"

  shop-db:
    ports:
      - "3303:3306"

  shop-redis:
    ports:
      - "6379:6379"
